version: '3'

services:
  mysql_db:
    image: mysql:5.7
    container_name: go_gorm_mux_bookstore_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 1306:3306
    expose:
      - 1306
    environment:
      # MYSQL_ROOT_HOST=localhost
      MYSQL_DATABASE: bookstore
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_db
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - bookstore

  app:
    container_name: go_gorm_mux_bookstore
    build: .
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - api:/usr/src/app/
    restart: on-failure
    environment:
      DB_HOST: mysql_db
      DB_DRIVER: mysql 
      DB_USER: 'admin'
      DB_PASSWORD: 'letmein'
      DB_NAME: bookstore
      DB_PORT: 3306
      SERVICE_TAGS: dev
      SERVICE_NAME: go_gorm_mux_bookstore 
      API_SECRET: "aksdjaskdjaskdls"

    depends_on:
      - mysql_db
    networks:
      - bookstore
  

volumes:
  api:
  mysql_db:

networks:
  bookstore:
    driver: bridge